version: '2.1'
services:
  db:
    restart: always
    container_name: marketplace_postgres
    image: postgres:10.1
    environment:
    - POSTGRES_DB=payments
    - POSTGRES_USER=payments
    - POSTGRES_PASSWORD=qwe123
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    build:
      context: ./
    volumes:
    - ./:/api
    environment:
    - NODE_ENV=development
    - DB_HOST=marketplace_postgres
    ports:
    - "80:80"
    links:
    - db